### ISSUE TITLE
Nommer correctement les fonctions

### ISSUE THREAD

**Issue by gabrielstuff** [HarlausG/Solaris#3]
la fonction getWeatherInfos s'occupe à la fois de récupérer l'infos du temps et d'envoyer sur la socket cette météo.

https://github.com/HarlausG/Solaris/blob/d102d870cab4da2f065bdedaeb066b3870c977e0/server.js#L46

**Comment by GauthierEd** [comment]
J'ai créé une fonction supplémentaire qui se charge uniquement d'envoyer sur la socket la météo
